const projectList = [
  {
    path: '/exercises/html-css/Signup',
    name: 'Signup',
    description: 'A basic signup page using HTML and CSS.',
    tags: ['#html', '#css', '#react'],
  },
  {
    path: '/exercises/html-css/Homepage',
    name: 'Websites',
    description: 'My collection of sample websites.',
    tags: ['#html', '#css', '#wordpress'],
  },
  {
    path: '/exercises/react/Invoice',
    name: 'Invoice App',
    description: 'A simple program for creating invoices.',
    tags: ['#html', '#css', '#js', '#business'],
  },
  {
    path: '/exercises/js/ProjectLibrary',
    name: 'Library catalogue',
    description: 'Catalog with books',
    tags: ['#html', '#css', '#js'],
  },
  {
    path: '/exercises/js/Fetch',
    name: 'Pokemon Cards',
    description: 'A project that demonstrates the use of the Fetch API.',
    tags: ['#js', '#fetch'],
  },
  {
    path: '/exercises/js/Bot',
    name: 'Bot',
    description: 'A basic bot application developed in JavaScript.',
    tags: ['#html', '#css', '#js'],
  },
  {
    path: '/exercises/js/Blockchain',
    name: 'Blockchain',
    description: 'An introduction to the fundamental concepts of blockchain.',
    tags: ['#js', '#blockchain'],
  },
  {
    path: '/exercises/js/Blockchain2',
    name: 'Voting App',
    description: 'A voting application built on blockchain technology.',
    tags: ['#js', '#blockchain'],
  },
  {
    path: '/exercises/js/Blockchain3',
    name: 'NFT',
    description: 'A basic NFT project based on blockchain technology.',
    tags: ['#js', '#blockchain', '#nft'],
  },
  {
    path: '/exercises/js/MachineLearning',
    name: 'Real Estate',
    description: 'Property price forecasting using machine learning.',
    tags: ['#js', '#ml'],
  },
  {
    path: '/exercises/js/MachineLearning2',
    name: 'Football',
    description: 'Predicting match outcomes using machine learning techniques.',
    tags: ['#js', '#ml'],
  },
  {
    path: '/exercises/js/HitTheMoleGame',
    name: 'Hit The Mole Game',
    description: 'A delightful hit-the-mole game developed in JavaScript.',
    tags: ['#js', '#react', '#game'],
  },
  {
    path: '/exercises/js/MemoGame',
    name: 'Memo Game',
    description: 'A memory card matching game.',
    tags: ['#js', '#react', '#game'],
  },
  {
    path: '/exercises/js/NoughtsAndCrosses',
    name: 'Noughts And Crosses',
    description: 'The classic Tic Tac Toe game implemented in JavaScript.',
    tags: ['#js', '#react', '#game'],
  },
  {
    path: '/exercises/react/GameSpace',
    name: 'Space Ship',
    description: 'A simple game about avoiding obstacles in space.',
    tags: ['#js', '#react', '#game'],
  },
  {
    path: '/exercises/js/football',
    name: 'Football',
    description: 'A game for predicting football match outcomes.',
    tags: ['#js', '#game'],
  },
  {
    path: '/exercises/react/BTC',
    name: 'BTC',
    description: 'Bitcoin valuation based on data from Coingecko.',
    tags: ['#react', '#fetch', '#crypto'],
  },
  {
    path: '/exercises/react/CRM',
    name: 'CRM',
    description: 'Simple CRM application',
    tags: ['#react', '#js', '#business'],
  },
  {
    path: '/exercises/react/MoonPhase',
    name: 'Moon Phase',
    description: 'A project that displays the moon phases for selected dates.',
    tags: ['#react', '#js', '#astronomy'],
  },
  {
    path: '/exercises/react/Planets',
    name: 'Planets',
    description: 'An educational project about the solar system.',
    tags: ['#react', '#js', '#astronomy'],
  },
  {
    path: '/exercises/react/Norris',
    name: 'Chuck Norris',
    description: 'Another project that demonstrates the use of the Fetch API.',
    tags: ['#react', '#fetch'],
  },
  {
    path: '/exercises/react/Calc',
    name: 'Calculator',
    description: 'Simple Calculator',
    tags: ['#js', '#react'],
  },
  {
    path: '/exercises/react/Hangman',
    name: 'Hangman',
    description: 'Classic word-guessing game',
    tags: ['#js', '#react'],
  },
  {
    path: '/exercises/react/Mastermind',
    name: 'Mastermind',
    description: 'Classic color-guessing game',
    tags: ['#js', '#react'],
  },
  {
    path: '/exercises/js/Spotify',
    name: 'Spotify',
    description: 'Simple music player',
    tags: ['#js', '#react', '#audio'],
  },
];

export default projectList;
